accounts/urls.py
# myblog/accounts/urls.py

from django.urls import path

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    # ex: /accounts/signup/
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/create/', views.CreateView.as_view(), name='create'),
    path('post/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('post/<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete/', views.DetailView.as_view(), name='delete'),
    path('post/help/', views.help, name='help'),
]

rankin/urls.py
from django.urls import path
from django.contrib import admin

assert isinstance(path,object )
from django.urls import include, path

urlpatterns = [
    path('', include('myapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField(default='')
    pub_date = models.DateField('date published')
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Choice(models.Model):
    select = models.ForeignKey(Post, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

myapp/views.py
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.views import generic
from django.shortcuts import redirect
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Post

"""
Django Auth
The LoginRequired mixin
https://docs.djangoproject.com/en/3.0/topics/auth/default/#the-loginrequired-mixin
The login_required decorator
https://docs.djangoproject.com/en/3.0/topics/auth/default/#the-login-required-decorator
@login_required
"""


class IndexView(generic.ListView):
    model = Post
    paginate_by = 5
    ordering = ['-updated_at']
    template_name = 'myapp/post_list.html'


class DetailView(generic.DetailView):
    model = Post
    template_name = 'myapp/post_confirm_delete.html'


class CreateView(LoginRequiredMixin, generic.edit.CreateView):  # The LoginRequired mixin
    model = Post
    fields = ['title', 'text']  # '__all__'

    template_name = 'myapp/post_form.html'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        # https://docs.djangoproject.com/en/3.0/topics/class-based-views/generic-editing/#models-and-request-user
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)


class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):  # The LoginRequired mixin
    model = Post
    fields = ['title', 'text']  # '__all__'

    template_name = 'myapp/post_form.html'

    def dispatch(self, request, *args, **kwargs):
        # ownership validation
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission to edit.')

        return super(UpdateView, self).dispatch(request, *args, **kwargs)


class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):  # The LoginRequired mixin
    model = Post
    success_url = reverse_lazy('myapp:index')
    template_name = 'myapp/post_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        # ownership validation
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission to delete.')

        return super(DeleteView, self).dispatch(request, *args, **kwargs)


@login_required
def help(request):
    return HttpResponse("Member Only Help Page")

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign up</h1>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Sign up</button>
    </form>
</section>
{% endblock %}

myapp/templates/myapp/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Post{% endblock %}

{% block content %}
<h1>Delete Post</h1>
<section class="common-form">
    <p>Are you sure you want to delete "{{ object.title }}" ?</p>
    <form action="" method="post">{% csrf_token %}
        <button type="submit" class="submit delete">Delete</button>
    </form>
</section>
<section>
    <p><a href="javascript:history.back()">&lt; Back</a></p>
</section>
{% endblock %}

myapp/templates/myapp/post_detail.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<h1>{{ object.title }}</h1>
<section class="post-text">
    {{ object.text|linebreaksbr }}
    <p>Author: {{ object.author }}</p>
</section>
<section class="post-date">
    <p>Created:&nbsp;{{ object.created_at }}<span>/</span>Updated:&nbsp;{{ object.updated_at }}</p>
</section>
{# ownership #}
{% if request.user.id == object.author_id %}
<section class="post-edit">
    <a class="act" href="{% url 'myapp:update' post.pk %}">Edit</a>
    <a class="act" href="{% url 'myapp:delete' post.pk %}">Delete</a>
</section>
{% endif %}
<section>
    <p><a href="javascript:history.back()">&lt; Back</a></p>
</section>
{% endblock %}

myapp/templates/myapp/post_form.html
{% extends 'base.html' %}

{% block title %}{{ object|yesno:'Edit,Add New'}} Post{% endblock %}

{% block content %}
{# https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#yesno #}
<h1>{{ object|yesno:'Edit,Add New'}} Post</h1>
<section class="common-form">
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">{{ object|yesno:'Update,Save'}}</button>
    </form>
</section>
{% endblock %}

myapp/templates/myapp/post_list.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<h1>Username</h1>
<p class="user-name">{{ user }}</p>
{% endif %}

<h1>Articles</h1>
<section class="post-list">
    <ul>
        {% for post in object_list %}
        <li>
            <h2><a href="{% url 'myapp:detail' post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text }}</p>
        </li>
        {% empty %}
        <li class="no-post">
            <p>No articles yet.</p>
            <p><a class="act" href="{% url 'myapp:create' %}">Add New Post</a></p></li>
        {% endfor %}
    </ul>
</section>

{% if is_paginated %}
<section class="pagination">
    <ul>
        <li>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt; Prev</a>
            {% else %}
            &lt;&lt; Prev
            {% endif %}
        </li>
        <li>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next &gt;&gt;</a>
            {% else %}
            Next &gt;&gt;
            {% endif %}
        </li>
    </ul>
</section>
{% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}Rankin with Auth | Django3 Tutorial</title>
</head>
<body>
<div class="container">
    <header>
        <p class="site-name"><a href="{% url 'myapp:index' %}">rankin</a></p>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="logout">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:signup' %}" class="signup">Sign up</a></li>
                <li><a href="{% url 'login' %}" class="login">Login</a></li>
                {% endif %}
                <li><a href="{% url 'myapp:create' %}" class="act">Add Post</a></li>
            </ul>
        </nav>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>